### ISSUE TITLE
groupIdについて

### ISSUE THREAD

**Issue by LazyGon** [okocraft/Spawners#2]
レポジトリがSiroPluginsやしろさんの個人レポならgroupIdはcom.github.siroshun09~でも良いんですが、okocraftレポにあるのならnet.okocraft.~にしたほうがいいと思いましたが、どうでしょうか

**Comment by Siroshun09** [comment]
単純に、最初は SiroPlugins 下に置くつもりで作ってて
作ってる途中にここに置いてほしいとのことだったのでこういうことに。
事の順番的にこうなってしまった
